using AcmeSalary.Api.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

builder.Services.AddCors(options =>
{
    options.AddPolicy("ReactApp", policy =>
    {
        policy.WithOrigins("http://localhost:5173")
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");

builder.Services.AddDbContext<AppDbContext>(options =>
{
    if (connectionString!.StartsWith("Host=", StringComparison.OrdinalIgnoreCase))
    {
        options.UseNpgsql(connectionString);
    }
    else
    {
        options.UseSqlite(connectionString);
    }
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors("ReactApp");

if (!app.Environment.IsProduction())
{
    app.UseHttpsRedirection();
}

app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();

    await dbContext.Database.MigrateAsync();

    // PostgreSQL requires identity generation for integer primary keys.
    if (connectionString!.StartsWith("Host=", StringComparison.OrdinalIgnoreCase))
    {
        await dbContext.Database.ExecuteSqlRawAsync("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Countries'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "Countries"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Departments'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "Departments"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Employees'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "Employees"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Salaries'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "Salaries"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'SalaryAudits'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "SalaryAudits"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;
            END
            $$;
        """);

        // If the previous deployment failed during seeding,
        // Countries/Departments may already exist while Employees are empty.
        // Remove the incomplete seed so it can start cleanly.
        var employeeCount = await dbContext.Employees.CountAsync();

        if (employeeCount == 0)
        {
            await dbContext.Database.ExecuteSqlRawAsync("""
                DELETE FROM "SalaryAudits";
                DELETE FROM "Salaries";
                DELETE FROM "Employees";
                DELETE FROM "Countries";
                DELETE FROM "Departments";
            """);
        }
    }

    await DbSeeder.SeedAsync(dbContext);
}

app.Run();