using AcmeSalary.Api.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

builder.Services.AddCors(options =>
{
    options.AddPolicy("ReactApp", policy =>
    {
       policy.WithOrigins(
    "http://localhost:5173",
    "https://acme-salary-management-1.onrender.com"
)
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");

builder.Services.AddDbContext<AppDbContext>(options =>
{
    if (connectionString!.StartsWith("Host=", StringComparison.OrdinalIgnoreCase))
    {
        options.UseNpgsql(connectionString);
    }
    else
    {
        options.UseSqlite(connectionString);
    }
});

var app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI();
app.UseCors("ReactApp");

if (!app.Environment.IsProduction())
{
    app.UseHttpsRedirection();
}

app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();

    await dbContext.Database.MigrateAsync();

    if (connectionString!.StartsWith("Host=", StringComparison.OrdinalIgnoreCase))
    {
        // PostgreSQL requires identity generation for integer primary keys.
        await dbContext.Database.ExecuteSqlRawAsync("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Countries'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "Countries"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Departments'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "Departments"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Employees'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "Employees"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Salaries'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "Salaries"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'SalaryAudits'
                      AND column_name = 'Id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    ALTER TABLE "SalaryAudits"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;
            END
            $$;
        """);

        // The original SQLite migrations created DateTime columns as TEXT.
        // Convert those existing PostgreSQL columns to timestamp with time zone.
        await dbContext.Database.ExecuteSqlRawAsync("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Employees'
                      AND column_name = 'HireDate'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "Employees"
                    ALTER COLUMN "HireDate"
                    TYPE timestamp with time zone
                    USING NULLIF("HireDate", '')::timestamp with time zone;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Employees'
                      AND column_name = 'CreatedAt'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "Employees"
                    ALTER COLUMN "CreatedAt"
                    TYPE timestamp with time zone
                    USING NULLIF("CreatedAt", '')::timestamp with time zone;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Employees'
                      AND column_name = 'UpdatedAt'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "Employees"
                    ALTER COLUMN "UpdatedAt"
                    TYPE timestamp with time zone
                    USING NULLIF("UpdatedAt", '')::timestamp with time zone;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Salaries'
                      AND column_name = 'EffectiveFrom'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "Salaries"
                    ALTER COLUMN "EffectiveFrom"
                    TYPE timestamp with time zone
                    USING NULLIF("EffectiveFrom", '')::timestamp with time zone;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Salaries'
                      AND column_name = 'EffectiveTo'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "Salaries"
                    ALTER COLUMN "EffectiveTo"
                    TYPE timestamp with time zone
                    USING NULLIF("EffectiveTo", '')::timestamp with time zone;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Salaries'
                      AND column_name = 'CreatedAt'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "Salaries"
                    ALTER COLUMN "CreatedAt"
                    TYPE timestamp with time zone
                    USING NULLIF("CreatedAt", '')::timestamp with time zone;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'SalaryAudits'
                      AND column_name = 'ChangedAt'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "SalaryAudits"
                    ALTER COLUMN "ChangedAt"
                    TYPE timestamp with time zone
                    USING NULLIF("ChangedAt", '')::timestamp with time zone;
                END IF;
                                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'SalaryAudits'
                      AND column_name = 'PreviousSalary'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "SalaryAudits"
                    ALTER COLUMN "PreviousSalary"
                    TYPE numeric
                    USING NULLIF("PreviousSalary", '')::numeric;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'SalaryAudits'
                      AND column_name = 'NewSalary'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "SalaryAudits"
                    ALTER COLUMN "NewSalary"
                    TYPE numeric
                    USING NULLIF("NewSalary", '')::numeric;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'SalaryAudits'
                      AND column_name = 'PreviousBonus'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "SalaryAudits"
                    ALTER COLUMN "PreviousBonus"
                    TYPE numeric
                    USING NULLIF("PreviousBonus", '')::numeric;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'SalaryAudits'
                      AND column_name = 'NewBonus'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "SalaryAudits"
                    ALTER COLUMN "NewBonus"
                    TYPE numeric
                    USING NULLIF("NewBonus", '')::numeric;
                END IF;
            END
            $$;
        """);

        // If the previous deployment failed during seeding,
        // Countries/Departments may already exist while Employees are empty.
        var employeeCount = await dbContext.Employees.CountAsync();

        if (employeeCount == 0)
        {
            await dbContext.Database.ExecuteSqlRawAsync("""
                DELETE FROM "SalaryAudits";
                DELETE FROM "Salaries";
                DELETE FROM "Employees";
                DELETE FROM "Countries";
                DELETE FROM "Departments";
            """);
        }
    }

    await DbSeeder.SeedAsync(dbContext);
}

app.Run();